### ISSUE TITLE
Login is successful but still always shows login page

### ISSUE THREAD

**Issue by 112madgamer** [antifuchs/htpasswd-login#5]
When you login a successful login is shown but when redirect you are shown the login page again. As if nginx is isn't aware you logged in?

```
2019/10/09 12:12:10 Validating login request by user "q" on "192.168.1.2"
2019/10/09 12:12:10 Authenticated, redirecting to "http://192.168.1.2/"
```

**Comment by 112madgamer** [comment]
Seems that this piece of code is causing it to fail
```
	session, err := srv.NewSession(r.Host, user)
	if err != nil {
		return
	}
```

**Comment by 112madgamer** [comment]
This seems of been fixed when I made the sessions directory. But now it doesn't redirect to the page the login page shows all the time

**Comment by antifuchs** [comment]
Oof, I missed this issue because I was unsubscribed from the repo for some reason - sorry.

This is weird, and probably means that there's something weird going on in the interaction between nginx and the process. What config did you use, and what does the nginx error log show?

As a step further, you can tcpdump the communication between the nginx and the htpasswd-login process via something like `sudo tcpdump -i lo -s0 -w /tmp/dumped-htpasswd-login-traffic.pcap port 8000` - running this while you go through the flow and then hitting Ctrl-C on the tcpdump process ought to write the raw traffic into the file `/tmp/dumped-htpasswd-login-traffic.pcap`, letting you inspect the HTTP requests either with a pager & squinting (which will look gross in a terminal), or via a tool like wireshark. (Beware that the traffic will likely contain credentials if you capture the login page as well).

One suspicion that I have here is that nginx isn't configured to send the Cookies header along to htpasswd-login; maybe capturing the traffic as above will show that this is the case.

**Comment by 112madgamer** [comment]
I have the pcap file if there is a way you want me to sure it with you.
The nginx error.log shows this 
```
2019/10/09 15:46:04 [error] 4933#4933: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.100, server: , request: "GET /favicon.ico HTTP/1.1", subrequest: "/auth", upstream: "http://[::1]:8000/auth", host: "192.168.1.2"
```
the auth config is just the default config you have on the repo

**Comment by 112madgamer** [comment]
Looks like it was the cookies not being sent added setting ```proxy_set_header                Cookie $http_cookie;``` worked

**Comment by antifuchs** [comment]
Thanks for the update! I'll update the example config! (And sorry for the trouble)
